<?php
/**
 * Implementation of hook_page_alter
 */
function google_analytics_event_tracking_page_alter(&$page) {
	require_once(drupal_get_path('module', 'googleanalytics') .'/googleanalytics.module');
	global $user;

  $id = variable_get('googleanalytics_account', '');

  // Get page status code for visibility filtering.
  $status = drupal_get_http_header('Status');
  $trackable_status_codes = array(
    '403 Forbidden',
    '404 Not Found',
  );

	$default_selectors = array(
		array(
			'selector' => '#main-menu li a',
			'category' => 'main navigation',
			'action' => 'click',
			'label' => '!text',
			'value' => 0,
			'noninteraction' => true,
		),
		array(
			'selector' => 'a#logo',
			'category' => 'Home Link',
			'action' => 'click',
			'label' => 'Logo',
			'value' => 0,
			'noninteraction' => true,
		),
		array(
			'selector' => 'div#site-name a[rel="home"]',
			'category' => 'Home Link',
			'action' => 'click',
			'label' => 'Site Name',
			'value' => 0,
			'noninteraction' => true,
		),
	);

	$js = array(
		'google_analytics_event_tracking_settings' => array(
			'selectors' => unserialize(variable_get('gaet_selectors', serialize($default_selectors))),
		),
	);

	if (!empty($id) && (_googleanalytics_visibility_pages() || in_array($status, $trackable_status_codes)) && _googleanalytics_visibility_user($user)) {
		// Get the page scope setting from googleanalytics:
    $scope = variable_get('googleanalytics_js_scope', 'header');
		drupal_add_js($js, 'setting');
		drupal_add_js(drupal_get_path('module', 'google_analytics_event_tracking') . '/js/gaet.js', array('scope' => $scope,));	
	}

}


/**
 * Set the selector variable
 * 
 * This function is intended to be used by glue code or features to set the event tracking without the
 * need of a complicated UI
 *
 * @param $selectors
 * The selectors array, this is a multidementional indexed array. Each element in the array is an array with
 * the following structure.
 * 	array(
 *		'selector' => (String)'p',
 *		'category' => 'String',
 *		'action' => 'String',
 *		'label' => 'String',
 *		'value' => Integer,
 *		'noninteraction' => Boolean,
 *	),
 * Read the README.txt file or visit http://code.google.com/apis/analytics/docs/tracking/eventTrackerGuide.html
 * for futher explanation.
 *
 * @return
 * If an no array is sent then it returns (bool)FALSE
 * If variable set is called then it returns (bool)TRUE
 */
function google_analytics_event_tracking_set_selectors($selectors) {
	if(!is_array($selectors)) {
		return FALSE;
	}
	vaiable_set('gaet_selectors', serialize($selectors));
	return TRUE;
}