<?php
/**
 * @file
 * Google Analytics Event Tracking Module API Example.
 *
 * Shows a quick and dirty example of how to integrate the Google Analytics
 * Event Tracking Module into an user's module.
 */

/**
 * Implements google_analytics_et_api
 */
function google_analytics_et_example_google_analytics_et_api() {
  return _google_analytics_et_example_set_selectors_array();
}

/**
 * Internal function returns the example selectors array.
 */
function _google_analytics_et_example_set_selectors_array() {
  $selectors = array();

  $selectors = array(
    array(
      'selector' => '#main-menu li a',
      'category' => 'main navigation',
      'action' => 'click',
      'label' => '!text',
      'value' => 0,
      'noninteraction' => TRUE,
    ),
    array(
      'selector' => 'a#logo',
      'category' => 'Home Link',
      'action' => 'click',
      'label' => 'Logo',
      'value' => 0,
      'noninteraction' => TRUE,
    ),
    array(
      'selector' => 'div#site-name a[rel="home"]',
      'category' => 'Home Link',
      'action' => 'click',
      'label' => 'Site Name',
      'value' => 0,
      'noninteraction' => TRUE,
    ),
    array(
      'selector' => 'p',
      'category' => 'test',
      'action' => 'click',
      'label' => '!test',
      'value' => 0,
      'noninteraction' => TRUE,
    ),
  );

  return $selectors;
}

